"production_url": "https://jeremyrsellars.github.io/no-new-legacy"
"base_path": "/no-new-legacy"

"posts":
  "sort": ["date", "desc"]
  stop_at_header: true
  summary_lines: 1

"pages":
  "sort": ["date", "desc"]

"theme-bootstrap-2":
  "use": "theme"
